In [1]:
import pandas as pd

from Package.Practice import display_menu

series = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon'])

# Creating the row axis labels
print(series)
series.index = ['City 1', 'City 1', 'City 3', 'City 3']

0    New York
1     Chicago
2     Toronto
3      Lisbon
dtype: object
City 1    New York
City 1     Chicago
City 3     Toronto
City 3      Lisbon
dtype: object

**Intro**
I am Ronish

In [2]:
print(series)

City 1    New York
City 1     Chicago
City 3     Toronto
City 3      Lisbon
dtype: object

In [8]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
print(df)
#df.insert(0, 'A', [5, 6],allow_duplicates=True)
print(df['A'][1])

   A  B
0  1  3
1  2  4
2

In [27]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)

subset = df.loc[0:,['Name', 'Age']]
print(subset)
print(df[(df['Age']>20) & (df['Salary']>50000)])
print(df.at[2,'Age'])
print(df['Age'].head(2))
print(df)
display("Hi")
display(df)

      Name  Age
0     John   25
1    Alice   30
2      Bob   22
3      Eve   35
4  Charlie   28
    Name  Age  Gender  Salary
1  Alice   30  Female   55000
3    Eve   35  Female   70000
22
0    25
1    30
Name: Age, dtype: int64
      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

'Hi'

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [28]:
display(df)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [43]:
import numpy as ron
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})
#display(dataFrame)
indx=ron.where(dataFrame['Salary']>95000)
print(indx)
print(dataFrame.loc[[0,3]])
print(dataFrame.iloc[[0,3]])

(array([0, 3]),)
         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
3    ROSS       33  120000  PALENTOLOGY
         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
3    ROSS       33  120000  PALENTOLOGY

In [49]:
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}
df = pd.DataFrame(data1, index=[0, 1, 2, 3])
df[df.loc[0]['Name']=='Jai']


data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}



df1 = pd.DataFrame(data2, index=[0, 1, 2, 3])
frames = [df, df1]
print(df, "\n\n", df1)
res1 = pd.concat(frames)
print(res1)
print(res1.iloc[0])

KeyError: True

In [58]:
data4 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}
df = pd.DataFrame(data4, index=[0, 1, 2, 3])
print(df.loc[0]['Name'])
print(df[df['Name'] == 'Jai']['Name'].iloc[0])
print(df.query("Name=='Jai'")['Name'].values)

Jai
Jai
['Jai']